# Generated by Django 4.2.2 on 2023-07-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='languageUsed1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='languageUsed2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='languageUsed3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='languageUsed4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
